-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(I.USER_ID)) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT(I.USER_ID))/(SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO

# ONLINE_SALE_ID, I.USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
FROM USER_INFO I JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY MONTH
ORDER BY YEAR ASC, MONTH ASC;